// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyN0-9iYuUf8rQl4lrBlvAoxpJB-qZVOc',
    appId: '1:387168571956:web:b064acc9305155eeebb061',
    messagingSenderId: '387168571956',
    projectId: 'edu-track-7d45f',
    authDomain: 'edu-track-7d45f.firebaseapp.com',
    storageBucket: 'edu-track-7d45f.firebasestorage.app',
    measurementId: 'G-CMQ951CZXG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnmvpzBlINK56CAvTQMmwaaWSYKGtii18',
    appId: '1:387168571956:android:b3fa820c710f0fe4ebb061',
    messagingSenderId: '387168571956',
    projectId: 'edu-track-7d45f',
    storageBucket: 'edu-track-7d45f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBez8lOCQQZj5jGEqx86vjNjXnCMJJzFZI',
    appId: '1:387168571956:ios:f5fffc83546267afebb061',
    messagingSenderId: '387168571956',
    projectId: 'edu-track-7d45f',
    storageBucket: 'edu-track-7d45f.firebasestorage.app',
    iosBundleId: 'com.example.eduuTrackk',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBez8lOCQQZj5jGEqx86vjNjXnCMJJzFZI',
    appId: '1:387168571956:ios:f5fffc83546267afebb061',
    messagingSenderId: '387168571956',
    projectId: 'edu-track-7d45f',
    storageBucket: 'edu-track-7d45f.firebasestorage.app',
    iosBundleId: 'com.example.eduuTrackk',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDyN0-9iYuUf8rQl4lrBlvAoxpJB-qZVOc',
    appId: '1:387168571956:web:55d8b229edb29a5aebb061',
    messagingSenderId: '387168571956',
    projectId: 'edu-track-7d45f',
    authDomain: 'edu-track-7d45f.firebaseapp.com',
    storageBucket: 'edu-track-7d45f.firebasestorage.app',
    measurementId: 'G-BK4ZZPJ88D',
  );
}
